import { StaticPage } from './StaticPage'

export function EducationalDisclaimerPage() {
  return (
    <StaticPage title="Educational disclaimer">
      <p>MaSign is a student project, built and maintained as coursework. It is not a registered company, a law firm, or a commercial product, and it comes with no service guarantee, support commitment, or warranty of any kind.</p>
      <p>
        Its answers and risk findings are generated by an AI model reading the text you upload. They are a starting point for
        understanding a contract, not legal advice, and should not be relied on as a substitute for review by a qualified professional
        before signing anything.
      </p>
      <p className="muted small">Verify anything that matters against the actual contract — every answer and finding links back to the exact passage it came from for that reason.</p>
    </StaticPage>
  )
}
