import { Fragment } from 'react'
import { PageChrome } from './components/PageChrome'

const STEPS = [
  {
    title: 'Upload',
    text: 'Add a contract — TXT, PDF or DOCX. MaSign reads it and splits it into passages.',
    icon: <path d="M12 3v12m0-12 4 4m-4-4-4 4M5 17v2a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-2" />,
  },
  {
    title: 'Review',
    text: 'MaSign starts a risk review and looks for key terms. Check its coverage before relying on a result.',
    icon: <path d="M12 3 2.5 20h19L12 3ZM12 9v4m0 3h.01" />,
  },
  {
    title: 'Check sources',
    text: 'Ask a question or open a finding, then read its cited passage in the contract.',
    icon: <path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8M8 17h5" />,
  },
]

const TRUST = [
  {
    title: 'Cited answers',
    text: 'Open the cited passage behind a grounded answer.',
    href: '/how-it-works',
    icon: <path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8M8 17h5" />,
  },
  {
    title: 'Risk review',
    text: 'See important contract terms that may need attention.',
    href: '/what-masign-checks',
    icon: <path d="M12 3 2.5 20h19L12 3ZM12 9v4m0 3h.01" />,
  },
  {
    title: 'Key terms',
    text: 'Find fees, dates, renewals, notice periods, and termination terms.',
    href: '/what-masign-checks',
    icon: <path d="M7 3v3m10-3v3M4 9h16M6 5h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Zm2 8h3m-3 4h5" />,
  },
  {
    title: 'Honest unknowns',
    text: 'See when information is missing or could not be checked.',
    href: '/how-it-works',
    icon: <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Zm0-12v4m0 3h.01" />,
  },
]

const EXPECTATIONS = [
  {
    title: 'Assists, not legal advice',
    text: 'MaSign supports your review of a contract; it does not replace a lawyer and does not make legal decisions.',
    icon: <path d="M12 3v18M5 7l-3 6a3 3 0 0 0 6 0L5 7Zm14 0-3 6a3 3 0 0 0 6 0l-3-6ZM5 7h14" />,
  },
  {
    title: 'AI findings may be imperfect',
    text: 'Answers and risk findings are generated by a model reading the uploaded text — verify anything that matters against the source passage each one links to.',
    icon: <path d="M12 3 2.5 20h19L12 3ZM12 9v4m0 3h.01" />,
  },
  {
    title: 'How your data is used',
    text: 'Passages relevant to a question or review are sent to the configured AI provider (Anthropic or OpenAI) to generate the answer or finding.',
    icon: <path d="M6 11V8a6 6 0 0 1 12 0v3M5 11h14v9H5z" />,
  },
]

// A static workspace illustration (MAS-147, refined in MAS-175). The visual
// follows the owner's reference, while its categories and statuses reflect
// real MaSign behaviour. It is hidden from assistive technology because the
// values describe an illustrative contract, not a reviewed user document.
function HeroMockup() {
  return (
    <div className="home-hero-mockup" aria-hidden="true">
      <div className="mockup-window mockup-window-wide">
        <div className="mockup-titlebar">
          <span className="mockup-dot" />
          <span className="mockup-dot" />
          <span className="mockup-dot" />
          <span className="mockup-titlebar-label">MaSign Workspace</span>
        </div>
        <div className="mockup-main">
          <div className="mockup-file-row">
            <div className="mockup-file-details">
              <div className="mockup-file-meta">
                <span className="mockup-filetype">PDF</span>
                <span className="mockup-filename">Master_Services_Agreement.pdf</span>
              </div>
              <h3>Master Services Agreement</h3>
            </div>
            <span className="mockup-reviewed">✓ Reviewed</span>
          </div>
          <div className="mockup-panel">
            <h4>Key terms extracted</h4>
            <dl className="mockup-terms">
              <div className="mockup-term"><dt>Recurring fee</dt><dd>EUR 4,200 / month</dd></div>
              <div className="mockup-term"><dt>Late-payment interest</dt><dd>1.5% / month <span className="mockup-deviation">Deviates</span></dd></div>
              <div className="mockup-term"><dt>Initial term</dt><dd>24 months</dd></div>
            </dl>
          </div>
          <div className="mockup-panel">
            <h4>Risk review</h4>
            <div className="mockup-risk mockup-risk-high">
              <div className="mockup-risk-head"><span className="mockup-severity">High risk</span><strong>Liability cap</strong><span className="mockup-source">Source →</span></div>
              <p>Vendor disclaims liability for its own data breaches entirely.</p>
            </div>
            <div className="mockup-risk mockup-risk-medium">
              <div className="mockup-risk-head"><span className="mockup-severity">Medium</span><strong>Termination</strong><span className="mockup-source">Source →</span></div>
              <p>Termination for convenience requires 90 days' written notice.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// The public home page (MAS-133): a real landing page, not the workspace.
// One job — explain what MaSign does and send a visitor to /workspace.
export function HomePage() {
  return (
    <PageChrome>
      <main className="content homepage">
        <section className="home-hero-row">
          <div className="hero home-hero">
            <p className="home-eyebrow">AI-assisted contract analysis</p>
            <h1>
              Understand <br />your contract <br />
              <span className="home-headline-highlight">before you sign.
                <svg viewBox="0 0 300 15" preserveAspectRatio="none" aria-hidden="true">
                  <path d="M2 12C52 5 110 2 151 3c53-1 100 1 139 5 5 1 7 3 5 4-42-3-97-4-144-3C100 9 49 12 2 15Z" fill="#0caded" opacity=".75" />
                </svg>
              </span>
            </h1>
            <p>
              MaSign helps you find important terms, review possible risks, and open the exact contract text behind each result.
            </p>
            <div className="home-cta-row">
              <a className="primary home-cta" href="/workspace">
                Open workspace
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M5 12h14M13 6l6 6-6 6" />
                </svg>
              </a>
              <a className="home-cta-secondary" href="/how-it-works">
                See how it works
              </a>
            </div>
          </div>
          <HeroMockup />
        </section>

        <section className="home-steps-section" aria-labelledby="how-it-works-title">
          <div className="home-proof-heading">
            <h2 id="how-it-works-title">How MaSign works</h2>
            <p>A clear first read of your contract, in three steps.</p>
          </div>
          <div className="home-steps-row">
            {STEPS.map((step, i) => (
              <Fragment key={step.title}>
                <div className="card home-step">
                  <div className="home-step-icon-wrap">
                    <span className="home-step-icon" aria-hidden="true">
                      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        {step.icon}
                      </svg>
                    </span>
                    <span className="home-step-number-badge" aria-hidden="true">
                      {i + 1}
                    </span>
                  </div>
                  <h3>{step.title}</h3>
                  <p>{step.text}</p>
                </div>
                {i < STEPS.length - 1 && (
                  <span className="home-step-arrow" aria-hidden="true">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M5 12h14M13 6l6 6-6 6" />
                    </svg>
                  </span>
                )}
              </Fragment>
            ))}
          </div>
        </section>

        <section className="home-proof" aria-labelledby="why-masign-title">
          <div className="home-proof-heading">
            <h2 id="why-masign-title">Why MaSign</h2>
            <p>A clear first read of your contract, with sources you can open.</p>
          </div>
          <div className="home-proof-grid">
            {TRUST.map((item) => (
              <a key={item.title} className="card home-proof-card" href={item.href}>
                <span className="home-proof-icon" aria-hidden="true">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    {item.icon}
                  </svg>
                </span>
                <h3>{item.title}</h3>
                <p>{item.text}</p>
                <span className="home-proof-card-arrow" aria-hidden="true">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M9 6l6 6-6 6" />
                  </svg>
                </span>
              </a>
            ))}
          </div>
          <a className="home-proof-cta" href="/workspace">
            Open workspace
          </a>
        </section>

        <section className="home-expectations" aria-labelledby="expectations-title">
          <div className="home-expectations-heading">
            <span className="home-expectations-icon" aria-hidden="true">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z" />
              </svg>
            </span>
            <h2 id="expectations-title">Clear expectations</h2>
          </div>
          <div className="home-expectations-grid">
            {EXPECTATIONS.map((item) => (
              <div key={item.title} className="home-expectation">
                <span className="home-expectation-icon" aria-hidden="true">
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    {item.icon}
                  </svg>
                </span>
                <div>
                  <h3>{item.title}</h3>
                  <p>{item.text}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="home-final-cta" aria-labelledby="home-final-cta-title">
          <div className="home-final-cta-inner">
            <div>
              <p className="home-final-cta-eyebrow">Start with the contract you have</p>
              <h2 id="home-final-cta-title">Ready to review a contract?</h2>
              <p>Upload a contract to see important terms, possible risks, and their source passages together.</p>
            </div>
            <a className="home-final-cta-button" href="/workspace">
              Open workspace
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M5 12h14M13 6l6 6-6 6" />
              </svg>
            </a>
          </div>
        </section>
      </main>
    </PageChrome>
  )
}
