import { Fragment } from 'react'
import { PageChrome } from './components/PageChrome'

const STEPS = [
  {
    title: 'Upload',
    text: 'Add a contract — TXT, PDF or DOCX. MaSign reads it and splits it into passages.',
    icon: <path d="M12 3v12m0-12 4 4m-4-4-4 4M5 17v2a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-2" />,
  },
  {
    title: 'Review',
    text: 'Every upload gets a whole-contract risk review and the key financial terms extracted, source included.',
    icon: <path d="M12 3 2.5 20h19L12 3ZM12 9v4m0 3h.01" />,
  },
  {
    title: 'Check sources',
    text: 'Ask a question or open a finding; every answer links back to the exact passage it came from.',
    icon: <path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8M8 17h5" />,
  },
]

const TRUST = [
  {
    title: 'Cited answers',
    text: 'Open the exact clause behind every answer.',
    href: '/how-it-works',
    icon: <path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8M8 17h5" />,
  },
  {
    title: 'Risk review',
    text: 'See important contract terms that may need attention.',
    href: '/what-masign-checks',
    icon: <path d="M12 3 2.5 20h19L12 3ZM12 9v4m0 3h.01" />,
  },
  {
    title: 'Key terms',
    text: 'Find fees, dates, renewals, notice periods, and termination terms.',
    href: '/what-masign-checks',
    icon: <path d="M7 3v3m10-3v3M4 9h16M6 5h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Zm2 8h3m-3 4h5" />,
  },
  {
    title: 'Honest unknowns',
    text: 'MaSign clearly says when the contract does not contain enough information.',
    href: '/how-it-works',
    icon: <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Zm0-12v4m0 3h.01" />,
  },
]

// A compact proof strip gives first-time visitors the three things that make
// MaSign useful before they reach the longer explanation below. These are
// existing behaviours, not quality, speed, or security claims.
const TRUST_STRIP = [
  {
    title: 'Source-linked answers',
    text: 'Open the clause behind a result.',
    icon: <path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8M8 17h5" />,
  },
  {
    title: 'Customer-side risk review',
    text: 'See terms that may need attention.',
    icon: <path d="M12 3 2.5 20h19L12 3ZM12 9v4m0 3h.01" />,
  },
  {
    title: 'Key terms together',
    text: 'Find fees, dates, renewal and notice.',
    icon: <path d="M7 3v3m10-3v3M4 9h16M6 5h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Zm2 8h3m-3 4h5" />,
  },
]

const EXPECTATIONS = [
  {
    title: 'Assists, not legal advice',
    text: 'MaSign supports your review of a contract; it does not replace a lawyer and does not make legal decisions.',
    icon: <path d="M12 3v18M5 7l-3 6a3 3 0 0 0 6 0L5 7Zm14 0-3 6a3 3 0 0 0 6 0l-3-6ZM5 7h14" />,
  },
  {
    title: 'AI findings may be imperfect',
    text: 'Answers and risk findings are generated by a model reading the uploaded text — verify anything that matters against the source passage each one links to.',
    icon: <path d="M12 3 2.5 20h19L12 3ZM12 9v4m0 3h.01" />,
  },
  {
    title: 'How your data is used',
    text: 'Passages relevant to a question or review are sent to the configured AI provider (Anthropic or OpenAI) to generate the answer or finding.',
    icon: <path d="M6 11V8a6 6 0 0 1 12 0v3M5 11h14v9H5z" />,
  },
]

// A static illustration of the real workspace (MAS-147), built from the same
// markup/classes the app renders (`.filetype`, `.risks`, `li.risk`,
// `.severity`, `.status`) so it looks like the product rather than an
// invented UI. Content is fixed and grounded in real behaviour, not
// arbitrary example text:
// - the AI-instructions notice uses CoverageNotice.tsx's exact copy
//   ("AI instructions detected · 1 passage withheld");
// - the risk findings use real rubric categories and severity thresholds
//   (app/risk_analysis/rubric.py: liability High needs an excluded-breach
//   clause, termination Medium needs notice over 60 days);
// - "Deviates" is KeyTermsCard.tsx's real standard-comparison status, not an
//   invented "higher than standard" label.
// It is static and captioned "Illustrative example": MaSign has no customer
// contracts to screenshot, and MAS-134 already decided this page claims
// nothing it can't back up.
function HeroMockup() {
  return (
    <div className="home-hero-mockup" aria-hidden="true">
      <div className="mockup-window mockup-window-wide">
        <div className="mockup-titlebar">
          <span className="mockup-dot" />
          <span className="mockup-dot" />
          <span className="mockup-dot" />
          <span className="mockup-titlebar-label">MaSign — Workspace</span>
        </div>
        <div className="mockup-workspace">
          <div className="mockup-sidebar">
            <div className="mockup-sidebar-item mockup-sidebar-item-active">
              <span className="filetype pdf">PDF</span>
              <span className="mockup-sidebar-name">Master_Services...</span>
            </div>
            <div className="mockup-sidebar-item">
              <span className="filetype docx">DOCX</span>
              <span className="mockup-sidebar-name">NDA_Vendor.docx</span>
            </div>
            <div className="mockup-sidebar-item">
              <span className="filetype txt">TXT</span>
              <span className="mockup-sidebar-name">Service_Agreement</span>
            </div>
          </div>
          <div className="mockup-main">
            <div className="mockup-file-row">
              <span className="mockup-filename">Master_Services_Agreement.pdf</span>
              <span className="status ok">Reviewed</span>
            </div>
            <p className="mockup-ai-notice">AI instructions detected · 1 passage withheld</p>
            <div className="mockup-panel">
              <h3>Key terms</h3>
              <dl className="mockup-terms">
                <div className="mockup-term">
                  <dt>Recurring fee</dt>
                  <dd>EUR 4,200 / month</dd>
                </div>
                <div className="mockup-term">
                  <dt>Late-payment interest</dt>
                  <dd>
                    1.5% / month <span className="status warn tiny">Deviates</span>
                  </dd>
                </div>
                <div className="mockup-term">
                  <dt>Initial term</dt>
                  <dd>24 months</dd>
                </div>
              </dl>
            </div>
            <div className="mockup-panel">
              <h3>Risk review</h3>
              <ul className="risks mockup-risks">
                <li className="risk severity-high">
                  <div className="risk-head">
                    <span className="severity">High</span>
                    <strong>Liability cap</strong>
                  </div>
                  <p className="risk-reason">Vendor disclaims liability for its own data breaches entirely.</p>
                </li>
                <li className="risk severity-medium">
                  <div className="risk-head">
                    <span className="severity">Medium</span>
                    <strong>Termination</strong>
                  </div>
                  <p className="risk-reason">Termination for convenience requires 90 days' written notice.</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <p className="mockup-caption">Illustrative example, not a real upload</p>
    </div>
  )
}

// The public home page (MAS-133): a real landing page, not the workspace.
// One job — explain what MaSign does and send a visitor to /workspace.
export function HomePage() {
  return (
    <PageChrome>
      <main className="content homepage">
        <section className="home-hero-row">
          <div className="hero home-hero">
            <p className="home-legal-notice">
              Educational tool — not legal advice. <a href="/educational-disclaimer">Full disclaimer</a>
            </p>
            <p className="home-eyebrow">AI-assisted contract analysis</p>
            <h1>
              Understand your contract <span className="glow">before you sign.</span>
            </h1>
            <p>
              MaSign helps you find important terms, review possible risks, and open the exact contract text behind every result.
            </p>
            <div className="home-cta-row">
              <a className="primary home-cta" href="/workspace">
                Open workspace
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M5 12h14M13 6l6 6-6 6" />
                </svg>
              </a>
              <a className="home-cta-secondary" href="/how-it-works">
                See how it works
              </a>
            </div>
            <p className="home-hero-microcopy muted small">Supports PDF, DOCX and TXT files</p>
          </div>
          <HeroMockup />
        </section>

        <section className="home-trust-strip" aria-label="What MaSign helps you do">
          {TRUST_STRIP.map((item) => (
            <div key={item.title} className="home-trust-item">
              <span className="home-trust-icon" aria-hidden="true">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  {item.icon}
                </svg>
              </span>
              <div>
                <h2>{item.title}</h2>
                <p>{item.text}</p>
              </div>
            </div>
          ))}
        </section>

        <section className="home-steps-section" aria-labelledby="how-it-works-title">
          <div className="home-proof-heading">
            <h2 id="how-it-works-title">How MaSign works</h2>
            <p>A clear first read of your contract, in three steps.</p>
          </div>
          <div className="home-steps-row">
            {STEPS.map((step, i) => (
              <Fragment key={step.title}>
                <div className="card home-step">
                  <div className="home-step-icon-wrap">
                    <span className="home-step-icon" aria-hidden="true">
                      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        {step.icon}
                      </svg>
                    </span>
                    <span className="home-step-number-badge" aria-hidden="true">
                      {i + 1}
                    </span>
                  </div>
                  <h3>{step.title}</h3>
                  <p>{step.text}</p>
                </div>
                {i < STEPS.length - 1 && (
                  <span className="home-step-arrow" aria-hidden="true">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M5 12h14M13 6l6 6-6 6" />
                    </svg>
                  </span>
                )}
              </Fragment>
            ))}
          </div>
        </section>

        <section className="home-proof" aria-labelledby="why-masign-title">
          <div className="home-proof-heading">
            <h2 id="why-masign-title">Why MaSign</h2>
            <p>A clear first read of your contract, with sources you can open.</p>
          </div>
          <div className="home-proof-grid">
            {TRUST.map((item) => (
              <a key={item.title} className="card home-proof-card" href={item.href}>
                <span className="home-proof-icon" aria-hidden="true">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    {item.icon}
                  </svg>
                </span>
                <h3>{item.title}</h3>
                <p>{item.text}</p>
                <span className="home-proof-card-arrow" aria-hidden="true">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M9 6l6 6-6 6" />
                  </svg>
                </span>
              </a>
            ))}
          </div>
          <a className="home-proof-cta" href="/workspace">
            Open workspace
          </a>
        </section>

        <section className="home-expectations" aria-labelledby="expectations-title">
          <div className="home-expectations-heading">
            <span className="home-expectations-icon" aria-hidden="true">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z" />
              </svg>
            </span>
            <h2 id="expectations-title">Clear expectations</h2>
          </div>
          <div className="home-expectations-grid">
            {EXPECTATIONS.map((item) => (
              <div key={item.title} className="home-expectation">
                <span className="home-expectation-icon" aria-hidden="true">
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    {item.icon}
                  </svg>
                </span>
                <div>
                  <h3>{item.title}</h3>
                  <p>{item.text}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="home-final-cta" aria-labelledby="home-final-cta-title">
          <div>
            <p className="home-final-cta-eyebrow">Start with the contract you have</p>
            <h2 id="home-final-cta-title">Ready to review a contract?</h2>
            <p>Upload a contract to see important terms, possible risks, and their source passages together.</p>
          </div>
          <a className="home-final-cta-button" href="/workspace">
            Open workspace
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <path d="M5 12h14M13 6l6 6-6 6" />
            </svg>
          </a>
        </section>
      </main>
    </PageChrome>
  )
}
